title: K4L1Ma
description: Notes on software craftsmanship, systems, and engineering.
url: "https://k4l1ma.github.io"
baseurl: "/blog"
author: Eduardo R Golding

image: /assets/og-software-craftsmanship.png

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /:year/:month/:day/:title/

header_pages: []

exclude:
  - Gemfile
  - Gemfile.lock